import React, { useState } from "react";
import Head from "next/head";
import style from './Header.module.css'
import "font-awesome/css/font-awesome.min.css";



const Header = () => {

  const menuLink = 'global_bottom_line_animation hover:text-white text-gray-400 text-base t-16 font-bold  px-3 py-2'
  return (
    <div>
      <Head>
        <title className= "logo">Doplax.Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/icon/site-icon.png"/>
      </Head>

      <header className=" py-6 w-full">
        <div className="container mx-auto flex justify-between items-center px-4">
          <a
            href="/"
            className={`${style.logo} ${style.navLink}`}
          > Doplax.Dev        
          </a>
          <nav>
            {/* Botón hamburguesa */}
            {/*<button
              className="block lg:hidden text-white focus:outline-none"
              onClick={toggleMenu}
            >
              BURGUER
            </button>*/}

            {/* Menú */}
            <ul
              //className={`${isMenuOpen ? "block" : "hidden"} lg:flex lg:space-x-4 space-y-2 lg:space-y-0`}
              className={"block lg:flex lg:space-x-4 space-y-2 lg:space-y-0"}

            >
              <li>
                <a
                  href="/"
                  className={menuLink}
                >
                  Home
                </a>
              </li>
              <li>
                <a
                  href="/sobreMi"
                  className={menuLink}
                  
                >
                  Sobre Mi
                </a>
              </li>
              <li>
                <a
                  href="/habilidades"
                  className={menuLink}

                >
                  Skills
                </a>
              </li>
              <li>
                <a
                  href="/contacto"
                  className={menuLink}

                >
                  Contacto
                </a>
              </li>
              <li>
                <a
                  href="/pruebas"
                  className={menuLink}

                >
                  Pruebas
                </a>
              </li>
            </ul>
          </nav>
        </div>
      </header>
    </div>
  );
};

export { Header };
