import React, { useState } from "react";
import Head from "next/head";
import "font-awesome/css/font-awesome.min.css";
import Image from "next/image";
import classNames from "classnames";


const Header = () => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const toggleMenu = () => {
    setIsMenuOpen(!isMenuOpen);  
  };

  const menuLink = 'global_bottom_line_animation text-white hover:text-gray-300 text-base t-16 font-bold  px-3 py-2'


  return (
    <div>
      <Head>
        <title>Doplax.Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className=" py-6 w-full">
        <div className="container mx-auto flex justify-between items-center px-4">
          <a
            href="/"
            className="bottom_line_animation text-white  text-base t-16 font-bold  px-3 py-2 "
          >
            <Image
              src="/img/logo-doplax.png"
              alt="Descripción de la imagen"
              width={200}
              height={200}
            />
          </a>
          <nav>
            {/* Botón hamburguesa */}
            {/*<button
              className="block lg:hidden text-white focus:outline-none"
              onClick={toggleMenu}
            >
              BURGUER
            </button>*/}

            {/* Menú */}
            <ul
              //className={`${isMenuOpen ? "block" : "hidden"} lg:flex lg:space-x-4 space-y-2 lg:space-y-0`}
              className={"block lg:flex lg:space-x-4 space-y-2 lg:space-y-0"}

            >
              <li>
                <a
                  href="/"
                  className={menuLink}
                >
                  HOME
                </a>
              </li>
              <li>
                <a
                  href="/sobreMi"
                  className={menuLink}
                  
                >
                  SOBRE MI
                </a>
              </li>
              <li>
                <a
                  href="/habilidades"
                  className={menuLink}

                >
                  HABILIDADES
                </a>
              </li>
              <li>
                <a
                  href="/contacto"
                  className={menuLink}

                >
                  CONTACTO
                </a>
              </li>
              <li>
                <a
                  href="/pruebas"
                  className={menuLink}

                >
                  PRUEBAS
                </a>
              </li>
            </ul>
          </nav>
        </div>
      </header>
    </div>
  );
};

export { Header };
