import Head from 'next/head'

import React from 'react';

const Header = () => {
  return (
    <div>

      <Head>
        <title>Doplax.Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="bg-gray-800 py-6">
        <div className="container mx-auto flex justify-between items-center px-4">
          <a href="/" className="text-white hover:rounded-full hover:bg-gray-300 hover:text-gray-800 px-3 py-2 transition-all duration-300">
            <h1 className="text-white font-bold text-xl">Mi sitio web</h1>
          </a>
          <nav>
            <ul className="flex space-x-4">
              <li>
                <a href="/" className="text-white hover:rounded-full hover:bg-gray-300 hover:text-gray-800 px-3 py-2 transition-all duration-300">Home</a>
              </li>
              <li>
                <a href="/sobreMi" className="text-white hover:rounded-full hover:bg-gray-300 hover:text-gray-800 px-3 py-2 transition-all duration-300">Sobre Mi</a>
              </li>
              <li>
                <a href="/habilidades" className="text-white hover:rounded-full hover:bg-gray-300 hover:text-gray-800 px-3 py-2 transition-all duration-300">Habilidades</a>
              </li>
              <li>
                <a href="/contacto" className="text-white hover:rounded-full hover:bg-gray-300 hover:text-gray-800 px-3 py-2 transition-all duration-300">Contacto</a>
              </li>
              <li>
                <a href="/pruebas" className="text-white hover:rounded-full hover:bg-gray-300 hover:text-gray-800 px-3 py-2 transition-all duration-300">Pruebas</a>
              </li>
            </ul>
          </nav>
        </div>
      </header>
    </div>

  );
};

export { Header };
