import '../styles/globals.css'
import { Inter } from 'next/font/google'
import { Footer } from '@/components/Layout/Footer/Footer';
import { Header } from '@/components/Layout/Header/Header';
import Head from "next/head";
import { Providers } from "./providers";

const inter = Inter({ subsets: ['latin'] })


// Es como si fuera un Json
export const metadata = {
  title: 'Doplax.dev',
  description: 'La web de pol valle',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Head>
        <title className="logo">Doplax.Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/src/app/favicon.ico" />
      </Head>

      <body className={`${inter.className} antialiased dark text-foreground `} >
        <Providers>

          <Header className='max-w-7xl mx-auto' />

          {/* Content */}
          <main className='max-w-7xl mx-auto px-4 sm:px-6 lg:px-8'>
            {children}
          </main>

          <Footer />
        </Providers>
      </body>
    </html>
  )
}




