import React  from "react";
import Head from "next/head";
import style from './Header.module.css' // Para hacer el Logo con ::afet y ::Before
import { HambBtn } from '@/components/UX/HambBtn/HambBtn'
//import "font-awesome/css/font-awesome.min.css";



const Header = () => {

  const menuLink = 'underLine_gAnimation hover:text-white text-gray-400 text-sm md:text-base font-bold  px-3 py-2'
  return (
    <>
      <Head>
        <title className= "logo">Doplax.Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/icon/site-icon.png"/>
      </Head>
      
      <header className="flex flex-wrap flex-row w-full justify-around items-center md:flex-row mx-0">
          {/* LOGO */}
          <a
            href="/"
            className={`${style.logo} ${style.navLink} `}
          > Doplax.Dev </a>
          
          <nav>
          
          

            <HambBtn/>
            {/* Menú */}
            {/*<ul
              className={"flex "}
            >
              <li>
                <a
                  href="/blog"
                  className={menuLink}
                  
                >
                  Blog
                </a>
              </li>

              <li>
                <a
                  href="/experiencia"
                  className={menuLink}
                >
                  Experiencia
                </a>
              </li>
              <li>
                <a href="/chatPage"
                  className={menuLink}
                > Chat </a>
              </li>
            </ul>*/}
          </nav>
      </header>
    </>
  );
};

export { Header };
