import React from "react";
import Head from "next/head";
import style from './Header.module.css' // Para hacer el Logo con ::afet y ::Before
import { HambBtn } from './HambBtn/HambBtn'
//import "font-awesome/css/font-awesome.min.css";



const Header = () => {

  const menuLink = 'text-lg md:text-base font-bold  px-3 py-4';
  const menuList = [
    {
      name: 'Blog',
      route: '/blog'
    },
    {
      name: 'Experience',
      route: '/experiencia'
    },
    {
      name: 'Chat',
      route: '/chat'
    },
  ]

  

  return (
    <>
      <Head>
        <title className="logo">Doplax.Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/icon/site-icon.png" />
      </Head>

      <header className="flex flex-wrap flex-row justify-between items-center md:flex-row ">
        {/* LOGO */}
        <a
          href="/"
          className={`${style.logo} ${style.navLink} `}> 
            Doplax.Dev 
        </a>

        {/* Mobile Menu */}
        <nav className="md:hidden">
          <HambBtn menuList={menuList}/>
        </nav>

        {/* Desktop Menu */}
        <nav className="hidden md:block">
          {/* Menú */}
          <ul className={"flex flex-row text-center"}>

            {menuList.map((element,index) => (
              <li key={index}>
                <a
                  href={element.route}
                  className={menuLink}
                >
                  {element.name}
                </a>
              </li>
            ))}

          </ul>
        </nav>
      </header>
    </>
  );
};

export { Header };
