import React from "react";
import Head from "next/head";
import style from './Header.module.css' // Para hacer el Logo con ::afet y ::Before
import { HambBtn } from '@/components/UX/HambBtn/HambBtn'
//import "font-awesome/css/font-awesome.min.css";



const Header = () => {

  const menuLink = 'text-lg md:text-base font-bold  px-3 py-4';

  return (
    <>
      <Head>
        <title className="logo">Doplax.Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/icon/site-icon.png" />
      </Head>

      <header className="flex flex-wrap flex-row justify-between items-center md:flex-row ">
        {/*className=' mx-auto px-4 sm:px-6 lg:px-8'*/}
        {/* LOGO */}
        <a
          href="/"
          className={`${style.logo} ${style.navLink} `}
        > Doplax.Dev </a>


        <nav className="md:hidden">
          <HambBtn />
        </nav>
        <nav className="hidden md:block">
          {/* Menú */}
          <ul
            className={"flex flex-row text-center"}
          >
            <li>
              <a
                href="/blog"
                className={menuLink}

              >
                Blog
              </a>
            </li>

            <li>
              <a
                href="/experiencia"
                className={menuLink}
              >
                Experiencia
              </a>
            </li>
            <li>
              <a href="/chatPage"
                className={menuLink}
              > Chat </a>
            </li>
          </ul>
        </nav>


      </header>
    </>
  );
};

export { Header };
